9th commit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -73,14 +73,14 @@ jobs:
           echo "Application is up and running with HTTP response code: $HTTP_RESPONSE"
         fi
 
-    - name: Rollback if URL check failed
-      if: failure()  # This will trigger if the previous URL check fails (exit 1)
-      run: |
-        echo "Rolling back deployment due to application URL failure."
-        kubectl --insecure-skip-tls-verify rollout undo deployment hmsconsole -n saas-dev
+    # - name: Rollback if URL check failed
+    #   if: failure()  # This will trigger if the previous URL check fails (exit 1)
+    #   run: |
+    #     echo "Rolling back deployment due to application URL failure."
+    #     kubectl --insecure-skip-tls-verify rollout undo deployment hmsconsole -n saas-dev
     
-    - name: Wait for 1 minute
-      run: sleep 60
+    # - name: Wait for 1 minute
+    #   run: sleep 60
   
     - name: Get Pod Name
       run: |
